version: '3.8'
services:
  auth_service:
    build: ./auth_service
    ports:
      - '5011:5011'
    restart: always

  orders_service:
    build: ./orders_service
    ports:
      - '5012:5012'
    restart: always
    depends_on:
      - auth_service
      
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - orders_service